<a href="https://colab.research.google.com/github/Souptikbej/Numpy-Class/blob/main/class6file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Broadcasting**

NumPy automatically adjusts array shapes so mathematical operations can work between arrays of different sizes.

In [2]:
import numpy as np

arr = np.array([1,2,3])

print(arr + 5) # NumPy automatically converted:5 into [5,5,5] and then do addition [1,2,3] + [5,5,5] = [6,7,8] and This automatic expansion is called: Broadcasting

[6 7 8]


## **Why Broadcasting Is Amazing ?**

Without broadcasting, you'd need loops:

```
for i in range(len(arr)):
    arr[i] += 5
```

NumPy avoids loops internally.

This makes computations MUCH faster.

## **Broadcasting Rules**

Two arrays can work together if:

**Rule 1** : Dimensions are equal

OR

**Rule 2** : One of them is 1

In [4]:
#Example 2 — Same Shape

a = np.array([1,2,3])
b = np.array([10,20,30])

print(a + b) # Here both array shape is (3,) and (3,) that,s why works perfectly.

[11 22 33]


In [5]:
#Example 3 — Different Shapes

a = np.array([[1],
              [2],
              [3]])

b = np.array([10,20,30])

print(a + b) # Here Shape of a:(3,1)  &  b:(3,) . So NumPy automatically expands arrays.

[[11 21 31]
 [12 22 32]
 [13 23 33]]


## **Broadcasting With 2D Arrays**

In [6]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print(a + b) # Here Numpy repeated [10 20 30] for each row . Internally:[[10 20 30] ,[10 20 30]] Then addition happens.

[[11 22 33]
 [14 25 36]]


## **When Broadcasting Failure ❌**

In [7]:
a = np.array([1,2,3])
b = np.array([1,2])

print(a + b)  # Because shape are different one is (3,) and another one is (2,) . So broadcasting fails.

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## **Broadcasting + reshape()**

VERY IMPORTANT COMBINATION.

In [8]:
a = np.array([1,2,3]).reshape(3,1)

b = np.array([10,20,30])

print(a + b) # Dimensions Compare From RIGHT SIDE . So Numpy reads : (3,1) , (1,3) . Then check (3,1)->ok , (1,3)->ok.

[[11 21 31]
 [12 22 32]
 [13 23 33]]
