<a href="https://colab.research.google.com/github/Souptikbej/Numpy-Class/blob/main/class2file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(3, 3)
2
9
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [11]:
arr=np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[5])
print(arr[-1])

1
6
6


Now lets see the 2D indexing aswell

In [16]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(arr[0])  #Print 1D array value

[1 2 3]


In [14]:
print(arr[2][2]) #Print 2D array value

9


Now we can also do the slicing lets see the **slicing in 1D**

In [15]:
arr=np.array([1,2,3,5,6])
arr[0:4]

[1 2 3 5]


1D slicing was really easy now lets see the **slicing in 2D**

In [22]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0:2,0:2]
arr[1:,1:]

array([[5, 6],
       [8, 9]])

There is one more thing known as **Boolean indexing**

In [25]:
arr=np.array([1,2,3,5,6,7,8,9,10])
print(arr>7)
print(arr[arr>7])

[False False False False False False  True  True  True]
[ 8  9 10]


In [26]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
print(arr>3)
print(arr[arr>3])

[[False False False]
 [ True  True  True]
 [ True  True  True]]
[4 5 6 7 8 9]


## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [31]:
arr=np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [33]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [34]:
a=np.array([10,20,30])
b=np.array([2,4,5])
a/b

array([5., 5., 6.])

In [35]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr[1]

array([4, 5, 6])