<a href="https://colab.research.google.com/github/Souptikbej/Numpy-Class/blob/main/class4file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [11]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90,100])

print("Original:", arr)

# Pick elements at positions 0,2,4,6,8
print("Fancy indexing:", arr[[0,2,4,6,8]])


Original: [ 10  20  30  40  50  60  70  80  90 100]
Fancy indexing: [10 30 50 70 90]


You can do this fancy indexing in 2D Matrix aswell

In [12]:
matrix = np.arange(1,13).reshape(3,4)
print("Matrix:\n", matrix)
print("Select [row0,col1], [row1,col2]:", matrix[[0,1],[1,2]])

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Select [row0,col1], [row1,col2]: [2 7]


##Conditional Selection
Find values based on conditions or replace them.

In [14]:
arr=np.array([5,12,30,7,60,9,10])
print(arr[arr>10])

# Indices where arr > 10
print(np.where(arr>10))

# Replace values: if >10 keep, else put 0
print(np.where(arr>10,arr,0))

[12 30 60]
(array([1, 2, 4]),)
[ 0 12 30  0 60  0  0]


##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [17]:
arr = np.array([42, 5, 18, 23])
print("Sorted:", np.sort(arr))

idx = np.argsort(arr)
print("Indices:", idx)
print("Use indices:", arr[idx])

Sorted: [ 5 18 23 42]
Indices: [1 2 3 0]
Use indices: [ 5 18 23 42]


In [20]:
mat = np.array([[3,7,1],[9,4,6]])
print(np.sort(mat, axis=1))   # sort each row
print(np.sort(mat, axis=0))   # sort each column

[[1 3 7]
 [4 6 9]]
[[3 4 1]
 [9 7 6]]


##Concatenation & Stacking

In [21]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

Vertical & Horizontal Stacking

In [22]:
print("vstack:\n", np.vstack((A,B)))   # vertical

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [23]:
print("hstack:\n", np.hstack((A,B)))   # horizontal

hstack:
 [[1 2 5 6]
 [3 4 7 8]]
