# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [10]:
a=[1,2,3,4,5]
arr=np.array(a)
arr

array([1, 2, 3, 4, 5])

Lets create a matrix using list

In [12]:
a=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(a)


Now lets see how matlix looks like using numpy arrays

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [17]:
arr=np.zeros([10,10])
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr=np.ones([5,5])
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
arr=np.full([4,4],2)
arr

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [21]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr=np.linspace(1,10,10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
arr=np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
arr=np.random.rand(5,5)
arr

array([[0.37994461, 0.7836885 , 0.55142379, 0.63672821, 0.8998337 ],
       [0.01117139, 0.62828755, 0.81286912, 0.99823703, 0.71920888],
       [0.11277984, 0.34486279, 0.94239556, 0.54732124, 0.75553003],
       [0.31300437, 0.66714146, 0.26731594, 0.83161702, 0.50662582],
       [0.14943257, 0.40608086, 0.15977144, 0.33038641, 0.09369531]])

In [29]:
arr=np.random.randint(1,10,(3,3))
arr

array([[1, 1, 4],
       [1, 3, 8],
       [5, 2, 4]])

In [32]:
arr=np.random.randn(1,3)
arr

array([[-1.15848501, -0.85329356,  1.06826412]])

In [33]:
arr=np.array([10,20,30])
arr+5

array([15, 25, 35])

In [34]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a1*a2

array([ 4, 10, 18])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution