<a href="https://colab.research.google.com/github/Souptikbej/Numpy-Class/blob/main/class5file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Shape Handling & Reshaping

In **Data Science**, data is mostly stored as arrays.

The biggest challenge is:

> “How do we arrange data into the correct shape?”

That’s why reshaping is critical.

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Example of 1D array : ",arr)
print("Check Shape : ",arr.shape)

Example of 1D array :  [1 2 3 4 5 6 7 8 9]
Check Shape :  (9,)


## ⭐1. reshape()

Used to change array dimensions.

In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9]) # Converting 1D -> 2D
new_arr=arr.reshape(3,3)
print("Example of 1D array :")
print(new_arr)
print("Check Shape : ",new_arr.shape)

Example of 1D array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Check Shape :  (3, 3)


### Important Rule

Total elements must remain SAME.

Example:

6 elements can become:
(2,3),
(3,2),
(1,6)

But NOT: (4,4)

Because 4×4 = 16 elements needed.

##reshape(-1,1)

Meaning:

1 column &
'n' rows

In [10]:
arr= np.array([1,2,3,4,5,6])
new_arr=arr.reshape(-1,1)
print(new_arr)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


##reshape(1,-1)

Meaning:

1 row &
'n' columns


In [12]:
print(new_arr.reshape(1,-1))

[[1 2 3 4 5 6]]


## ⭐2. flatten()

Converts multi-dimensional array → 1D array.

In [17]:
arr = np.array([[1,2,3],
                [4,5,6]])
flat = arr.flatten()
print(flat)

[1 2 3 4 5 6]


## ⭐3. ravel()

Similar to flatten().

In [18]:
arr = np.array([[1,2,3],
                [4,5,6]])
rav = arr.ravel()
print(rav)

[1 2 3 4 5 6]


## ⭐4. transpose()

Converts:
Rows ↔ Columns

In [19]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


## ⭐5. squeeze()

Removes unnecessary dimensions.

Sometimes datasets contain extra useless dimensions.

squeeze() removes them.

In [24]:
arr = np.array([[[1,2,3]]])
print("Unnecessary Dimensions",arr)
new_arr = np.squeeze(arr)
print("Removing unnecessary dimensions",new_arr)

Unnecessary Dimensions [[[1 2 3]]]
Removing unnecessary dimensions [1 2 3]


## ⭐6. expand_dims()

Adds new dimension.

In [27]:
arr = np.array([1,2,3])

new_arr = np.expand_dims(arr, axis=0) #axis=0 means Add rows
print(new_arr)
print(new_arr.shape)

new_arr = np.expand_dims(arr, axis=1) #axis=1 means Add columns
print(new_arr)
print(new_arr.shape)

[[1 2 3]]
(1, 3)
[[1]
 [2]
 [3]]
(3, 1)
