<a href="https://colab.research.google.com/github/Souptikbej/Numpy-Class/blob/main/class9file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Random Module**

## **⭐ 1. rand()**

Generates random decimal numbers between:

In [1]:
import numpy as np

print(np.random.rand())  #Every run gives different values within 0 and 1.

0.955121366636293


Multiple Random Values

In [2]:
print(np.random.rand(5))

[0.98059511 0.96452903 0.96598288 0.71608056 0.76513002]


2D Random Array

In [4]:
print(np.random.rand(3,3))

[[0.48866483 0.65483041 0.73880799]
 [0.3029968  0.92649987 0.64039218]
 [0.35563168 0.23532757 0.79698571]]


## **⭐ 2. randint()**

Generates random INTEGER values.

In [8]:
print("Single Integer : ",np.random.randint(1,10))

print("Multiple Integers : ",np.random.randint(1,10,5))

print("2D Integer Array  : \n",np.random.randint(1,100,(3,4)))

Single Integer :  5
Multiple Integers :  [4 1 5 2 1]
2D Integer Array  : 
 [[44 92 47 97]
 [41 85 37 85]
 [ 5  2 51 21]]


## **⭐ 3. seed()**

Controls randomness.

**Problem Without seed()**

- Every run gives different output.

- Sometimes we want SAME results.

In [11]:
np.random.seed(42)

print(np.random.randint(1,100,5))

[52 93 15 72 61]


## **⭐ 4. choice()**

Randomly selects values.

In [13]:
arr = [10,20,30,40]

print(np.random.choice(arr))

print(np.random.choice(arr, 3))  #Multiple Choices

30
[20 30 30]


## **⭐ 5. shuffle()**

Shuffles ORIGINAL array.

In [14]:
arr = np.array([1,2,3,4,5])

np.random.shuffle(arr) #shuffle() changes original array.

print(arr)

[4 2 1 5 3]


## **⭐ 6. permutation()**

Similar to shuffle().

BUT:

- does NOT modify original array

In [15]:
arr = np.array([1,2,3,4,5])

new_arr = np.random.permutation(arr)

print(new_arr)
print(arr)

[5 4 1 2 3]
[1 2 3 4 5]


## **⭐ 7. uniform()**

Random decimal values between range.

In [16]:
print(np.random.uniform(1,10,5))

[7.49798895 9.44697438 1.00700889 9.92990403 6.55733359]


## **⭐ 7. normal()**

Generates values from Normal Distribution.

Very important in AI/ML.

**Simple Meaning**

*Creates data around a mean.*

*Most real-world data follows normal distribution.*

Examples:

- Heights
- Marks
- Salaries
- Sensor data

In [17]:
data = np.random.normal(50, 10, 5) # (mean, standard_deviation, total_values)

print(data) #50 = center , 10 = spread , 5 = number of values

[50.22221827 45.72207086 44.6818259  48.82524498 52.22078902]
