<a href="https://colab.research.google.com/github/Souptikbej/Numpy-Class/blob/main/class7file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Boolean Masking & Filtering**

***Boolean means:*** True or False

***Masking means:*** Filtering data using conditions

In [13]:
#Example 1 — Basic Filtering
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr > 25)

[False False  True  True  True]


## **What Happened?**

NumPy checked each value:



```
Value	Condition(>25)	 Result

10	    False	          ❌

20	    False	          ❌
  
30	    True	          ✅

40	    True	          ✅

50	    True	          ✅
```



This True/False array is called: **Boolean Mask**

In [14]:
#Real Filtering

#Now use that mask to extract data.

print(arr[arr > 25])  #MOST IMPORTANT SYNTAX

[30 40 50]


In [15]:
#Example 2 — Less Than

print(arr[arr < 40])

[10 20 30]


In [16]:
#Example 3 — Equal To

print(arr[arr == 30])

[30]


In [17]:
#Example 4 — Not Equal

print(arr[arr != 20])

[10 30 40 50]


In [18]:
#Exapmle 5 - AND Condition

print(arr[(arr > 20) & (arr < 50)])

[30 40]


In [19]:
#Exapmle 5 - OR Condition

print(arr[(arr < 20) | (arr > 40)])

[10 50]


In [20]:
#Exapmle 5 - NOT Condition

print(arr[~(arr > 30)])

[10 20 30]


### **Boolean Masking with 2D Arrays**

In [21]:
data = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,90]])

print("Without Extracted Data: ")
print(data > 50)

print("Extracted Data: ")
print(data[data > 50])  #IMPORTANT Result becomes: 1D array after filtering.

Without Extracted Data: 
[[False False False]
 [False False  True]
 [ True  True  True]]
Extracted Data: 
[60 70 80 90]


# **Filtering Rows in 2D Arrays**

In [22]:
data = np.array([[50,60],
                 [20,30],
                 [80,90]])

print(data[data[:,0] > 40])  #data[:,0] Means: all rows of first column .Result: [50 20 80] -> Condition: [True False True] -> So selected rows: [[50 60] , [80 90]]

[[50 60]
 [80 90]]


### **⭐ np.where()**

*Very useful.*

Syntax: *np.where(condition, true_value, false_value)*



In [23]:
arr = np.array([10,20,30,40,50,60,70,80,90])

result= np.where(arr>50,"Pass","Fail")

print(result)

['Fail' 'Fail' 'Fail' 'Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass']
