<a href="https://colab.research.google.com/github/Souptikbej/Numpy-Class/blob/main/class3file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [2]:
import numpy as np

a= np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])

print(a+b)
print(a-b)
print(a//b)
print(a*b)

[11 22 33 44 55]
[ 9 18 27 36 45]
[10 10 10 10 10]
[ 10  40  90 160 250]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [3]:
a=np.array([1,2,3,4,5])

print(a*2)

[ 2  4  6  8 10]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [4]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a*2)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [5]:
a=np.array([5,20,31,95,63,45,80])
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.var(a))


339
48.42857142857143
5
95
30.208121627219693
912.5306122448981


You can also do the axis based operations row-Wise and Colum-wise

In [6]:
data=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.sum(data))

45


In [7]:
print(np.sum(data,axis=1))


[ 6 15 24]
