<a href="https://colab.research.google.com/github/Souptikbej/Numpy-Class/blob/main/practice2file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practice Exercises**

**Exercise 1**


```
a = np.array([1,2,3])

print(a + 10)
```


Predict output.

In [2]:
import numpy as np

a = np.array([1,2,3])

print(a + 10)

[11 12 13]


**Exercise 2**

```
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print(a + b)
```



Understand HOW broadcasting happens.

In [4]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print(a + b) # Here a shape is (2,3) & b shape is (3,) . So b internly convert into [[10,20,30],[10,20,30]] , now shape is (2,3) . In that way Broadcasting happend easily.

[[11 22 33]
 [14 25 36]]


**Exercise 3**

Try:



```
a = np.array([1,2,3]).reshape(3,1)

b = np.array([10,20,30])

print(a + b)
```



Visualize expansion.

In [5]:
a = np.array([1,2,3]).reshape(3,1)

b = np.array([10,20,30])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


### **Mini Project Practice**

Create:

```
np.random.randint(1,100,(5,3))
```
Then:


*   Add 10 to all values
*   Multiply each column differently
*   Subtract column mean



This is REAL Data Science preprocessing.

In [10]:
arr=np.random.randint(1,100,(5,3))
print("Before Doing any oparations :")
print(arr)

print("After Add 10 to all values :")
print(arr+10)

print("After Multiply each column differently :")
print(arr*arr)

print("After Subtract column mean :")
col_mean=arr.mean(axis=0)
print(arr-col_mean)


Before Doing any oparations :
[[15 33 39]
 [88 54 28]
 [89  4 30]
 [65 57 75]
 [69  9 59]]
After Add 10 to all values :
[[25 43 49]
 [98 64 38]
 [99 14 40]
 [75 67 85]
 [79 19 69]]
After Multiply each column differently :
[[ 225 1089 1521]
 [7744 2916  784]
 [7921   16  900]
 [4225 3249 5625]
 [4761   81 3481]]
After Subtract column mean :
[[-50.2   1.6  -7.2]
 [ 22.8  22.6 -18.2]
 [ 23.8 -27.4 -16.2]
 [ -0.2  25.6  28.8]
 [  3.8 -22.4  12.8]]


**Explations:**




1.   Add 10 to all values

Here we are add 10 to each values


```
[10 10 10        [2 3 9
 10 10 10    +    6 5 1
 10 10 10]        4 6 7]
```



2.   Multiply each column differently

Her we multiply same array like
```
[2 3 9        [2 3 9
 6 5 1    X    6 5 1
 4 6 7]        4 6 7]
```

3.   Subtract column mean

Here we

**Step 1: Find column mean**

So:

First column mean:

(2 + 6 + 4) / 3 = 4

Second column mean:

(3 + 5 + 6) / 3 = 4.6

Third column mean:

(9 + 1 + 7) / 3 = 5.6

**Step 2: Subtract column mean**

```
[2-4   3-4.6    9-5.6         [-2  -1.6   -3.4
 6-4   5-4.6    1-5.6      =    2   0.4   -4.6
 4-4   6-4.6    7-5.6]          0   1.4    1.4]
```
