<a href="https://colab.research.google.com/github/Souptikbej/Numpy-Class/blob/main/practice4file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practice Exercises**

**Exercise 1**

`arr = np.array([5,10,15,20,25])`

Find:

- mean
- median
- std
- max

In [2]:
import numpy as np
arr = np.array([5,10,15,20,25])

print("Mean of this array is : ",np.mean(arr))
print("Median of this array is : ",np.median(arr))
print("Standard Diviation of this array is : ",np.std(arr))
print("maximun value of this array is : ",np.max(arr))

Mean of this array is :  15.0
Median of this array is :  15.0
Standard Diviation of this array is :  7.0710678118654755
maximun value of this array is :  25


**Exercise 2**

```
data = np.array([[10,20],
                 [30,40],
                 [50,60]])
```

Find:

- column mean
- row mean

In [3]:
data = np.array([[10,20],
                 [30,40],
                 [50,60]])

col_mean = np.mean(data,axis=0)
row_mean = np.mean(data,axis=1)

print("Column Mean : ",col_mean)
print("Row Mean : ",row_mean)

Column Mean :  [30. 40.]
Row Mean :  [15. 35. 55.]


**Exercise 3**

Find:

- 25th percentile
- 75th percentile

In [4]:
data = np.array([[10,20],
                 [30,40],
                 [50,60]])

print("25th percentile : ",np.percentile(data,25))
print("75th percentile : ",np.percentile(data,75))

25th percentile :  22.5
75th percentile :  47.5


## **Mini Challenge**

Create:

`np.random.randint(1,100,(5,4))`

Then calculate:

- Overall mean
- Column mean
- Row mean
- Maximum value
- Standard deviation
- 75th percentile

In [6]:
arr = np.random.randint(1,100,(5,4))
print(arr)
print("Overall mean : ",np.mean(arr))
print("Column mean : ",np.mean(arr,axis=0))
print("Row mean : ",np.mean(arr,axis=1))
print("Maximum value : ",np.max(arr))
print("Standard deviation : ",np.std(arr))
print("75th percentile : ",np.percentile(arr,75))

[[79 58 55  8]
 [97 71 33 37]
 [34 77 60 20]
 [63 13 99 40]
 [12 41 40 14]]
Overall mean :  47.55
Column mean :  [57.  52.  57.4 23.8]
Row mean :  [50.   59.5  47.75 53.75 26.75]
Maximum value :  99
Standard deviation :  27.043437281529137
75th percentile :  65.0
