<a href="https://colab.research.google.com/github/Souptikbej/Numpy-Class/blob/main/practice1file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practice Exercises**

**Exercise 1**

Convert:

`[1,2,3,4,5,6,7,8]`

Into:

`(2,4)`

In [4]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8])

new_arr= arr.reshape(2,4)

print(new_arr)

print("Shape : ",new_arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
Shape :  (2, 4)


**Exercise 2**

Transpose:

```
 [[1,2],
 [3,4],
 [5,6]]
```

In [5]:
arr=np.array( [[1,2],
 [3,4],
 [5,6]])

new_arr=arr.T
print(new_arr)

[[1 3 5]
 [2 4 6]]


**Exercise 3**

Convert 2D array → 1D using:

flatten()

ravel()

In [7]:
arr=np.array( [[1,2],
 [3,4],
 [5,6]])

new_arr=arr.flatten()
print("Convert 2D array → 1D using flatten() : ",new_arr)

new_arr=arr.ravel()
print("Convert 2D array → 1D using ravel() : ",new_arr)

Convert 2D array → 1D using flatten() :  [1 2 3 4 5 6]
Convert 2D array → 1D using ravel() :  [1 2 3 4 5 6]


### **Mini Challenge**

Create:

```
np.arange(1,13)
```
Then:

*   reshape into (3,4)
*   transpose it
*   flatten it again











In [10]:
arr=np.arange(1,13)
print("After not apply any operation : ", arr)

new_arr=arr.reshape(3,4)
print("Before apply reshape into (3,4) : ")
print(new_arr)

new_arr=new_arr.T
print("Before apply transpose it : ")
print(new_arr)

new_arr=new_arr.flatten()
print("Before apply flatten it again : ")
print(new_arr)

After not apply any operation :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Before apply reshape into (3,4) : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Before apply transpose it : 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Before apply flatten it again : 
[ 1  5  9  2  6 10  3  7 11  4  8 12]
