<a href="https://colab.research.google.com/github/Souptikbej/Numpy-Class/blob/main/practice3file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practice Exercises**

**Exercise 1**

```
arr = np.array([5,10,15,20,25,30])
```

Get:

values > 15

values <= 20

In [3]:
import numpy as np
arr = np.array([5,10,15,20,25,30])
new_array = arr[arr > 15]
print(new_array)
new_array = arr[arr <= 20]
print(new_array)
#

[20 25 30]
[ 5 10 15 20]


**Exercise 2**


```
arr[(arr > 10) & (arr < 30)]
```

Predict output.

In [4]:
new_array=arr[(arr > 10) & (arr < 30)]
print(new_array)

[15 20 25]


**Exercise 3**



```
data = np.array([[10,20],
                 [50,60],
                 [70,80]])
```

Get rows where first column > 40.

In [5]:
data = np.array([[10,20],
                 [50,60],
                 [70,80]])
new_array=data[data[:,0] > 40]
print(new_array)

[[50 60]
 [70 80]]


## **Mini Challenge**

Create:



```
np.random.randint(1,100,20)
```



Then:

Find even numbers

Find odd numbers

Find values > 50

Remove values < 20

Replace values > 80 with 100 using np.where()

In [7]:
arr = np.random.randint(1,100,20)
print(arr)

print("\nEven numbers:")
print(arr[arr % 2 == 0])

print("\nOdd numbers:")
print(arr[arr % 2 != 0])

print("\nValues > 50:")
print(arr[arr > 50])

print("\nValues < 20:")
print(arr[arr < 20])

arr = np.where(arr > 80, 100, arr)
print("\nValues > 80 replaced with 100:")
print(arr)

[38 76 86 38 69 51 96 30 84 61 62 63 58 32 80 64 59 31 46 72]

Even numbers:
[38 76 86 38 96 30 84 62 58 32 80 64 46 72]

Odd numbers:
[69 51 61 63 59 31]

Values > 50:
[76 86 69 51 96 84 61 62 63 58 80 64 59 72]

Values < 20:
[]

Values > 80 replaced with 100:
[ 38  76 100  38  69  51 100  30 100  61  62  63  58  32  80  64  59  31
  46  72]
